version: 0.1

phases:
  build:
    commands:
      - echo nothning
      artifacts:
        files:
          - index.html
          - favicon.ico
          - images/*
          - Sushilkumar Nikam Resume.doc
          - styles/main.css
