version: 0.1

phases:
  install:
    commands:
      - printenv
  build:
    commands:
      - echo
  post_build:
    commands:
      - echo post build

artifacts:
  files:
    - index.html
    - favicon.ico
    - images/*
    - Sushilkumar Nikam Resume.doc
    - styles/main.css
